name: On Pull Request Opened

on:
  pull_request:
    branches: [ master ]

jobs:
  prettier:
    name: Prettier Formatter
    uses: ./.github/workflows/prettier.yml

  test:
    name: Testing
    uses: ./.github/workflows/test.yml