# .github/workflows/prettier.yml
name: Prettier Formatting

on:
  push:
    branches:
      - '*'  # Runs for pushes to any branch
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write
  statuses: write
  actions: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    outputs:
      prettier_changed: ${{ steps.check_changes.outputs.prettier_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to check for changes
          ref: ${{ github.ref }}  # Use ref for push events, which refers to the branch being pushed

      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prettier_options: --write '**/*.{js,jsx,ts,tsx}'

      - name: Check if Prettier made any changes
        id: check_changes
        run: |
          # Check for any changes after running Prettier
          git diff --exit-code || echo "prettier_changed=true" >> $GITHUB_ENV
          echo "prettier_changed=${{ env.prettier_changed }}" >> $GITHUB_OUTPUT

      - name: Commit and push changes if needed
        if: ${{ steps.check_changes.outputs.prettier_changed == 'true' }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Apply Prettier formatting"
          git push origin ${{ github.ref }}  # Push changes back to the branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
