name: Prettier Formatter

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  workflow_dispatch: # Allows manual triggering of the workflow

concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

permissions:
  contents: write
  statuses: write
  actions: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get-commit-sha.outputs.commit_sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Prettify Code
        uses: creyD/prettier_action@v4.3
        with:
          github_token: ${{ secrets.GIRAF_PAT }}  # Correct PAT token here
          prettier_options: --write '**/*.{js,jsx,ts,tsx}'


          

