# .github/workflows/tests.yml
name: Run Tests

on:
  push:
    branches:
      - '*'  # Runs for pushes to any branch
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write
  statuses: write
  actions: write

jobs:
  tests:
    runs-on: ubuntu-latest
    needs: prettier  # Ensure this job runs after Prettier
    if: ${{ needs.prettier.outputs.prettier_changed != 'true' }}  # Only run tests if Prettier didn't change anything
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to check for changes
          ref: ${{ github.ref }}  # Use ref for push events, which refers to the branch being pushed

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build --if-present

      - name: Run Tests
        run: npm run test-ci
