name: Node.js CI

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Build Application
        run: npm run build --if-present
      - name: Run Tests
        run: npm run test-ci

  prettier:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      statuses: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prettier_options: --write '**/*.{js,jsx,ts,tsx}'