on:
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  statuses: write
  actions: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get-commit-sha.outputs.commit_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prettier_options: --write '**/*.{js,jsx,ts,tsx}'

      - name: Get Commit SHA
        id: get-commit-sha
        run: echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  tests:
    needs: prettier  # This ensures tests start only after prettier completes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code from Prettier
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.prettier.outputs.commit_sha }}

      # Optional delay to ensure GitHub processes any new commit
      - name: Wait for changes to register
        run: sleep 20

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build --if-present

      - name: Run Tests
        run: npm run test-ci
