name: Testing

on:
  workflow_call:
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write
  statuses: write
  actions: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: refToHead
        run: echo $GITHUB_ENV
      # Use the commit SHA from the Prettier job to checkout the latest commit
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build --if-present

      - name: Run Tests
        run: npm run test-ci